# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import InventoryProto_pb2 as InventoryProto__pb2


class InventoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_book = channel.unary_unary(
                '/InventoryService/create_book',
                request_serializer=InventoryProto__pb2.Book.SerializeToString,
                response_deserializer=InventoryProto__pb2.CreateBookResponse.FromString,
                )
        self.get_book = channel.unary_unary(
                '/InventoryService/get_book',
                request_serializer=InventoryProto__pb2.ISBN.SerializeToString,
                response_deserializer=InventoryProto__pb2.Book.FromString,
                )


class InventoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_book(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_book(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_book': grpc.unary_unary_rpc_method_handler(
                    servicer.create_book,
                    request_deserializer=InventoryProto__pb2.Book.FromString,
                    response_serializer=InventoryProto__pb2.CreateBookResponse.SerializeToString,
            ),
            'get_book': grpc.unary_unary_rpc_method_handler(
                    servicer.get_book,
                    request_deserializer=InventoryProto__pb2.ISBN.FromString,
                    response_serializer=InventoryProto__pb2.Book.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/InventoryService/create_book',
            InventoryProto__pb2.Book.SerializeToString,
            InventoryProto__pb2.CreateBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/InventoryService/get_book',
            InventoryProto__pb2.ISBN.SerializeToString,
            InventoryProto__pb2.Book.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
