# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InventoryProto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14InventoryProto.proto\"&\n\x12\x43reateBookResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\x14\n\x04ISBN\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\"\xae\x01\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x1f\n\x05genre\x18\x04 \x01(\x0e\x32\x10.Book.genre_enum\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\"?\n\ngenre_enum\x12\n\n\x06\x43OMEDY\x10\x00\x12\n\n\x06HORROR\x10\x01\x12\x0c\n\x08THRILLER\x10\x02\x12\x0b\n\x07MYSTERY\x10\x03\"v\n\rInventoryItem\x12\x18\n\x10inventory_number\x18\x01 \x01(\t\x12\x0f\n\x05title\x18\x02 \x01(\tH\x00\x12\x0e\n\x04ISBN\x18\x03 \x01(\tH\x00\"\"\n\x06status\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x42\x06\n\x04\x62ook2W\n\x10InventoryService\x12)\n\x0b\x63reate_book\x12\x05.Book\x1a\x13.CreateBookResponse\x12\x18\n\x08get_book\x12\x05.ISBN\x1a\x05.Bookb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InventoryProto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEBOOKRESPONSE._serialized_start=24
  _CREATEBOOKRESPONSE._serialized_end=62
  _ISBN._serialized_start=64
  _ISBN._serialized_end=84
  _BOOK._serialized_start=87
  _BOOK._serialized_end=261
  _BOOK_GENRE_ENUM._serialized_start=198
  _BOOK_GENRE_ENUM._serialized_end=261
  _INVENTORYITEM._serialized_start=263
  _INVENTORYITEM._serialized_end=381
  _INVENTORYITEM_STATUS._serialized_start=339
  _INVENTORYITEM_STATUS._serialized_end=373
  _INVENTORYSERVICE._serialized_start=383
  _INVENTORYSERVICE._serialized_end=470
# @@protoc_insertion_point(module_scope)
